# Generated by Django 6.0 on 2026-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='City Not Specified', max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_url', models.URLField(default='https://example.com/default.jpg')),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Approval', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TouristSpot',
        ),
    ]
