# tour_spots/data.py
# Uttar Pradesh ke mashhoor Tourist Spots ka data.
# Location data (Latitude/Longitude) Google Maps se verified hai.

UP_TOURIST_SPOTS = [
    {
        'name': 'Taj Mahal',
        'city': 'Agra',
        'description': 'White marble mausoleum, one of the seven wonders of the world, built by Emperor Shah Jahan.',
        'category': 'Historical',
        'latitude': '27.175015',
        'longitude': '78.042155',
        'image_url': 'https://example.com/taj_mahal.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Agra Fort',
        'city': 'Agra',
        'description': 'A historical fort in the city of Agra, served as the main residence of the emperors of the Mughal Dynasty.',
        'category': 'Historical',
        'latitude': '27.181206',
        'longitude': '78.007624',
        'image_url': 'https://example.com/agra_fort.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Fatehpur Sikri',
        'city': 'Agra',
        'description': 'A city founded by Mughal emperor Akbar, famous for Buland Darwaza and Jama Masjid.',
        'category': 'Historical',
        'latitude': '27.090632',
        'longitude': '77.668388',
        'image_url': 'https://example.com/fatehpur_sikri.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Bada Imambara',
        'city': 'Lucknow',
        'description': 'A majestic shrine complex known for its amazing architecture and the famous Bhul Bhulaiya (Labyrinth).',
        'category': 'Historical',
        'latitude': '26.8674',
        'longitude': '80.9134',
        'image_url': 'https://example.com/bada_imambara.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Rumi Darwaza',
        'city': 'Lucknow',
        'description': 'An imposing gateway in the centre of Lucknow, built in the Awadhi style of architecture.',
        'category': 'Historical',
        'latitude': '26.8687',
        'longitude': '80.9126',
        'image_url': 'https://example.com/rumi_darwaza.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Janeshwar Mishra Park',
        'city': 'Lucknow',
        'description': 'A large urban park in Lucknow, established in memory of late politician Janeshwar Mishra. Largest park in Asia.',
        'category': 'Park',
        'latitude': '26.8485',
        'longitude': '81.0255',
        'image_url': 'https://example.com/janeshwar_park.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Kashi Vishwanath Temple',
        'city': 'Varanasi',
        'description': 'One of the holiest and most famous Hindu temples dedicated to Lord Shiva, located on the western bank of the river Ganga.',
        'category': 'Religious',
        'latitude': '25.3106',
        'longitude': '83.0101',
        'image_url': 'https://example.com/kashi_vishwanath.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Sarnath',
        'city': 'Varanasi',
        'description': 'A sacred Buddhist site where Buddha first taught the Dharma.',
        'category': 'Religious',
        'latitude': '25.3745',
        'longitude': '83.0185',
        'image_url': 'https://example.com/sarnath.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Prem Mandir',
        'city': 'Vrindavan',
        'description': 'A huge temple dedicated to Radha Krishna, known for its sheer magnificence and intricate carvings.',
        'category': 'Religious',
        'latitude': '27.5925',
        'longitude': '77.6749',
        'image_url': 'https://example.com/prem_mandir.jpg',
        'status': 'Approved',
    },
    {
        'name': 'Chandra Shekhar Azad Park (Alfred Park)',
        'city': 'Prayagraj',
        'description': 'The largest park in Prayagraj, historical significance as the site of Chandra Shekhar Azad\'s death.',
        'category': 'Park',
        'latitude': '25.4402',
        'longitude': '81.8487',
        'image_url': 'https://example.com/azad_park.jpg',
        'status': 'Approved',
    },
]